### PR TITLE
Explanation how to achieve `-p` in systemd.

### PR DESCRIPTION
**Pull request by SvobodaJakub**
Resolves https://github.com/rfjakob/earlyoom/issues/215

### CODE REVIEW

**Comment by rfjakob** [comment]
Excellent, thanks!

**Comment by GreatEmerald** [comment]
But then shouldn't this (just `-p` in general) just be the default? I don't see why you wouldn't use it by default for a tool like this.

**Comment by rfjakob** [comment]
My concern (and why I did not make it the default) is that then earlyoom may interrupt some low-latency process (video playback, network streaming etc) and degrade user experience

**Comment by GreatEmerald** [comment]
Does that happen in reality? Also, I'd expect that to be the reason to have it as an option, but I'd still think that people who install earlyoom are more likely to be server admins who are not running realtime apps, rather than musicians etc.

**Pull request merged**
