### PR TITLE
Update GUI helper

### PR DESCRIPTION
**Pull request by hakavlad**

### CODE REVIEW

**Comment by hakavlad** [comment]
- Native search envs without run `ps`
- Native send environment in subprocess without run `env`
- Popen is not deprecated. Use Popen (need Python 3.3, works on old systems out of the box) instead of run (need Python 3.5)

**Comment by hakavlad** [comment]
- more selective imports
- print info if nobody logged-in

**Comment by hakavlad** [comment]
- exclude Display Manager's user from search

**Comment by hakavlad** [comment]
This script already works great in nohang https://github.com/hakavlad/nohang/blob/master/nohang_notify_helper and help to show OOM preventing reports and Low memory warnings. Tested on Deb 8, Deb 9, Ub 1804, Fed 29.

**Comment by rfjakob** [comment]
Question, is `DISPLAY` actually needed? As far as I know, notify-send only talks to dbus. I tried it here on Fedora, and it works without DISPLAY.

**Comment by hakavlad** [comment]
It not works without DISPLAY. (I tested it now).

**Comment by hakavlad** [comment]
It not works on Deb 9:

```
#!/usr/bin/env python3
#
# Usage:
#   ./nohang_notify_helper "title" "body"

from sys import argv
from os import listdir
from subprocess import Popen, TimeoutExpired

if len(argv) < 2 or argv[1] == "-h" or argv[1] == "--help":
    print('Usage: ./nohang_notify_helper "title" "body"')
    exit(1)

wait_time = 12

dbus_env = 'DBUS_SESSION_BUS_ADDRESS='
user_env = 'USER='


def rline1(path):
    """read 1st line from path."""
    with open(path) as f:
        for line in f:
            return line


def re_pid_environ(pid):
    """
    read environ of 1 process
    returns tuple with USER, DBUS like follow:
    ('user',  'DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus')
    returns None if these vars is not in /proc/[pid]/environ
    """
    try:
        env = str(rline1('/proc/' + pid + '/environ'))
        if dbus_env in env and user_env in env:
            env_list = env.split('\x00')

            # iterating over a list of process environment variables
            for i in env_list:
                if i.startswith(user_env):
                    user = i
                    continue

                if i.startswith(dbus_env):
                    dbus = i
                    continue

                if i.startswith('HOME='):
                    # exclude Display Manager's user
                    if i.startswith('HOME=/var'):
                        return None

            env = user.partition('USER=')[2], dbus
            return env

    except FileNotFoundError:
        return None
    except ProcessLookupError:
        return None


def root_notify_env():
    """return set(user, dbus)"""
    unsorted_envs_list = []
    # iterates over processes, find processes with suitable env
    for pid in listdir('/proc'):
        if pid[0].isdecimal() is False:
            continue
        one_env = re_pid_environ(pid)
        unsorted_envs_list.append(one_env)
    env = set(unsorted_envs_list)
    env.discard(None)

    # deduplicate dbus
    new_env = []
    end = []
    for i in env:
        key = i[0]
        if key not in end:
            end.append(key)
            new_env.append(i)
        else:
            continue

    return new_env


list_with_envs = root_notify_env()

print(list_with_envs)


# if somebody logged in with GUI
if len(list_with_envs) > 0:
    # iterating over logged-in users
    for i in list_with_envs:
        username, dbus_env = i[0], i[1]
        dbus_tuple = dbus_env.partition('=')
        dbus_key, dbus_value = dbus_tuple[0], dbus_tuple[2]

        with Popen(['sudo', '-u', username,
                    'notify-send', '--icon=dialog-warning',
                     argv[1], argv[2]
                     ], env={
            dbus_key: dbus_value
        }) as proc:
            try:
                proc.wait(timeout=wait_time)
            except TimeoutExpired:
                proc.kill()
                print('TimeoutExpired: notify' + username)
else:
    print('Nobody logged-in with GUI. Nothing to do.')
```

**Comment by hakavlad** [comment]
It not works on Xubuntu 18.10.
User, display and dbus found, but notifications are not shown.

**Comment by hakavlad** [comment]
1. Seems like env={...} cause a problem. Solution: use old way: ['env', display_env, dbus_env]
2. It can works without DISPLAY.

Dirty fix: http://okturing.com/src/5719/body

**Comment by hakavlad** [comment]
Removing DISPLAY is a bad idea:
if user will be logged on 2 tty (for example, tty6 and tty7), then notificatin will be shown even on one of two tty.

**Comment by hakavlad** [comment]
Maybe it can possible to write universal wrapper (notify-send-root-wrapper), and use it via `-N notify-send-root-wrapper` without change C code.

**Pull request merged**
