### PR TITLE
Merge Debian/Ubuntu compatibility, fix logged process name and check return values

### PR DESCRIPTION
**Pull request by mikkorantalainen**
Merge following fixes:

- Build: implement Debian/Ubuntu compatibility
- userspace_kill: fix display of victim process name
- Hardening: check return value of system() and fscanf()
- Debian: use dh-systemd (Debian helper for systemd)

### CODE REVIEW

**Comment by rfjakob** [comment]
Fixes look good, thanks!

About the Debian changes: Are you in contact with Yangfl (current maintainer acc. to https://tracker.debian.org/pkg/earlyoom)? I'm not sure adding the "debian" directory to upstream is desirable.

**Comment by rfjakob** [comment]
@yangfl Do you have an opinion on that?

**Comment by yangfl** [comment]
Well, upstream's debian/ directory is always ignored by the packaging program (i.e. debhelper), so changes on the upstream side will virtually have no impact on current package (both in Debian and Ubuntu).
And as for the makefile, these values are deliberately chosen so that it will not conflict with any (potentially existing) package manager. /usr/local is recommended by the LSB as user's custom program.
The others just look good (and have nothing to do with packing :p).

**Comment by rfjakob** [comment]
@mikkorantalainen I have merged

* userspace_kill: fix display of victim process name
* Hardening: check return value of system() and fscanf()

but not the other two. I think the Makefile should install to /usr/local, and the deb packaging seems to be already handled well at https://anonscm.debian.org/git/collab-maint/earlyoom.git/tree/debian .

Thanks for the PR!

**Comment by mikkorantalainen** [comment]
I'm okay with not picking debian patches here. I was not aware of existing Debian packaging project for earlyoom so I wrapped my own package to install earlyoom on my systems as a real package. I think my implementation had better (simpler) implementation of some debian specific files (e.g. debian/rules) but as long as the resulting package works, I'm okay with any version. In addition, the existing debian package may be missing scripts to enable/disable the systemd service on install/remove/purge.

**Pull request closed without merging**
