### PR TITLE
Improve experience on servers

### PR DESCRIPTION
**Pull request by nailgun**
I've added some changes to improve earlyoom experience when running on servers.

1. Added Dockerfile (many people use docker to run stuff on servers)
2. As most servers have very large amount of RAM compared to desktop (64+ GiB), setting minimal memory value in percents of all RAM is not always a good idea, so I added options to set it in absolute value
3. Added `-r` option to control amount of stdout spam
4. Set maximum priority of earlyoom process
5. Set oom_score_adj to -1000 of earlyoom process on startup

### CODE REVIEW

**Comment by rfjakob** [comment]
Hi, thanks for the pull request! Some comments on the changes:

1) I like the addition of `-M` and `-S`. But the default value should stay at 10% as it was before. People are already relying on the default value.

2) Regarding `-r`, I wonder if `-q` (quiet) may be more useful? If `-q` is passed, only print something when we kill a process. I'm also fine with `-r` if you think it is more useful. Please call it "memory report interval", and the argument should be in seconds. This way the user does not have to know the scan interval that earlyoom uses internally.

3) I'm sceptical with `setpriority` and `oom_score_adj`: The first problem is that starting it as a normal user throws warning messages. The second problem is that if earlyoom itself leaks memory or goes into an infinite loop, it will kill the box. I personally have never seen that earlyoom is killed by the OOM killer (earlyoom uses so little memory, it's basically invisible to the OOM killer), so I wonder if this is an actual problem.

**Comment by nailgun** [comment]
Hi! Thanks for comments!

1. OK I'll restore default behavior.
2. OK
3. Actually I've added this because I use earlyoom in Kubernetes cluster and by default it sets oom_score_adj of all containers to 999... So may be leave it as an option? Also, I didn't see a `pid == getpid()` check in `userspace_kill` function. Is this intended?

**Comment by nailgun** [comment]
Hey @rfjakob. I've updated the PR as you suggest

**Comment by rfjakob** [comment]
Ok thanks for the update! Three more things:

1) The help text still says `default 262144 KiB`, should be 10 %
2) Please allow `-r 0` to disable reports altogether
3) Please squash your changes to only four commits, one for each topic (Dockerfile, absolute memory values, report delay, priority)

**Comment by nailgun** [comment]
Why? I don't like idea to loose history. Just merge with --no-ff and it will be atomic.

**Comment by rfjakob** [comment]
The Linux kernel does it the same: Only the final version of patch series is merged. Intermediate states are not very interesting and make following changes harder.

**Comment by rfjakob** [comment]
PS: Don't forget https://github.com/smpio/earlyoom/blob/master/main.c#L116

**Comment by nailgun** [comment]
Done

**Comment by rfjakob** [comment]
Merged to master, thanks! -> https://github.com/rfjakob/earlyoom/commits/master

**Pull request closed without merging**
